name: 自动编译

on:
  repository_dispatch:
  push:
    paths:
      - 'Dockerfile'
      - 'my_collectors/**'
      - 'node_exporter/**'
  workflow_dispatch:
    inputs:
      build:
        description: '编译 node_exporter 插件'
        required: true
        default: '编译 node_exporter 插件'
  schedule:
    - cron: '0 21 * * *'
  watch:
    types: [started]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id

    steps:
      - name: 检出代码（包含子模块）
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: 设置 Go 环境
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: 缓存 Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: 自动注册自定义采集器
        run: |
          bash my_collectors/auto_register_collectors.sh

      - name: 编译 node_exporter 主程序
        run: |
          cd node_exporter
          go mod tidy
          go build -o node_exporter

      # 多平台二进制文件编译
      - name: 构建多平台二进制文件
        run: |
          cd node_exporter
          mkdir -p .build/linux-amd64 .build/linux-arm64
          GOOS=linux   GOARCH=amd64  go build -o .build/linux-amd64/node_exporter
          GOOS=linux   GOARCH=arm64  go build -o .build/linux-arm64/node_exporter

      # 上传所有平台的二进制文件到 GitHub Actions 构建产物区
      - name: 上传多平台二进制文件
        uses: actions/upload-artifact@v4
        with:
          name: node_exporter-binaries
          path: |
            node_exporter/.build/linux-amd64/node_exporter
            node_exporter/.build/linux-arm64/node_exporter

      - name: 设置 QEMU（支持多平台 Docker 构建）
        uses: docker/setup-qemu-action@v3

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录 DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 登录 GitHub 容器仓库（ghcr.io）
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: 构建并推送 Docker 镜像到 DockerHub 和 ghcr.io
        uses: docker/build-push-action@v6
        with:
          file: 'node_exporter/Dockerfile'
          platforms: linux/amd64,linux/arm64
          context: ./node_exporter
          push: true
          tags: |
            ${{ github.repository_owner }}/node_exporter:latest
            ghcr.io/${{ github.repository_owner }}/node_exporter:latest 
