name: 编译 node_exporter 插件

on:
  repository_dispatch:
  push:
    paths:
      - 'Dockerfile'
      - 'my_collectors/**'
      - 'node_exporter/**'
  workflow_dispatch:
    inputs:
      build:
        description: '编译 node_exporter 插件'
        required: true
        default: '编译 node_exporter 插件'
  schedule:
    - cron: '0 21 * * *'
  watch:
    types: [started]

permissions:
  contents: write
  actions: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id

    steps:
      - name: 检出代码（包含子模块）
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: 设置 Go 环境
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: 缓存 Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: 自动注册自定义采集器
        run: |
          bash my_collectors/auto_register_collectors.sh

      # 安装 promu 构建工具
      - name: 安装 promu
        working-directory: node_exporter
        run: |
          # 获取最新版本的 promu
          PROMU_VERSION=$(curl -s https://api.github.com/repos/prometheus/promu/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed 's/v//')
          GO_BUILD_PLATFORM=linux-amd64
          PROMU_URL="https://github.com/prometheus/promu/releases/download/v${PROMU_VERSION}/promu-${PROMU_VERSION}.${GO_BUILD_PLATFORM}.tar.gz"

          echo "Installing promu version: ${PROMU_VERSION}"
          mkdir -p ~/go/bin
          curl -fsS -L ${PROMU_URL} | tar -xvzf - -C /tmp
          cp /tmp/promu-${PROMU_VERSION}.${GO_BUILD_PLATFORM}/promu ~/go/bin/
          chmod +x ~/go/bin/promu
          echo "$HOME/go/bin" >> $GITHUB_PATH

          # 验证安装
          promu --help

      # 多平台二进制文件编译（使用 promu crossbuild）
      - name: 构建多平台二进制文件（静态编译）
        working-directory: node_exporter
        env:
          CGO_ENABLED: 0
        run: |
          go mod tidy
          # 使用 promu crossbuild 构建多平台二进制文件
          promu crossbuild -v

      # 上传所有平台的二进制文件到 GitHub Actions 构建产物区
      - name: 上传多平台二进制文件
        uses: actions/upload-artifact@v4
        with:
          name: node_exporter-binaries
          path: |
            node_exporter/.build/linux-amd64/node_exporter
            node_exporter/.build/linux-arm64/node_exporter
            node_exporter/.build/openbsd-amd64/node_exporter

      - name: 设置 QEMU（支持多平台 Docker 构建）
        uses: docker/setup-qemu-action@v3

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录 DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 登录 GitHub 容器仓库（ghcr.io）
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: 构建并推送多平台 Docker 镜像到 DockerHub 和 ghcr.io
        uses: docker/build-push-action@v5
        with:
          file: node_exporter/Dockerfile
          context: ./node_exporter
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            ARCH=amd64
            OS=linux
          tags: |
            ${{ github.repository_owner }}/node_exporter:latest
            ghcr.io/${{ github.repository_owner }}/node_exporter:latest

      - name: 重命名产物以避免同名
        run: |
          # 重命名 Linux 平台的二进制文件
          if [ -f "node_exporter/.build/linux-amd64/node_exporter" ]; then
            mv node_exporter/.build/linux-amd64/node_exporter node_exporter/.build/linux-amd64/node_exporter-linux-amd64
          fi
          if [ -f "node_exporter/.build/linux-arm64/node_exporter" ]; then
            mv node_exporter/.build/linux-arm64/node_exporter node_exporter/.build/linux-arm64/node_exporter-linux-arm64
          fi
          if [ -f "node_exporter/.build/openbsd-amd64/node_exporter" ]; then
            mv node_exporter/.build/openbsd-amd64/node_exporter node_exporter/.build/openbsd-amd64/node_exporter-openbsd-amd64
          fi

      - name: 发布到 GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Release
          files: |
            node_exporter/.build/linux-amd64/node_exporter-linux-amd64
            node_exporter/.build/linux-arm64/node_exporter-linux-arm64
            node_exporter/.build/openbsd-amd64/node_exporter-openbsd-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 清理旧 Releases
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 删除 workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1

